name: Automated RCA

on:
  issues:
    types: [closed]

permissions:
  issues: write
  contents: read

jobs:
  automated-rca:
    name: Automated RCA
    runs-on: ubuntu-latest
    steps:
      - name: Automated RCA
        uses: MetaMask/github-tools/.github/actions/post-gh-rca@v1
        with:
          repo-owner: ${{ github.repository_owner }}
          repo-name: ${{ github.event.repository.name }}
          issue-number: ${{ github.event.issue.number }}
          issue-labels: '["Sev0-urgent", "Sev1-high"]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
