name: Check Changelog

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog:
    name: Check Changelog
    runs-on: ubuntu-latest
    # Asking engineers to update CHANGELOG.md increases the potential for
    # conflicts across all pull requests.
    # Disable this workflow until we can refine the new changelog process.
    if: false
    steps:
      - name: Check changelog
        uses: MetaMask/github-tools/.github/actions/check-changelog@v1
        with:
          base-branch: ${{ github.event.pull_request.base.ref }}
          head-ref: ${{ github.head_ref }}
          labels: ${{ toJSON(github.event.pull_request.labels) }}
          pr-number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
