name: ChangeLog Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check-changelog:
    uses: MetaMask/github-tools/.github/workflows/changelog-check.yml@changelog-checker
    with:
      base-branch: main
      feature-branch: ${{ github.head_ref }}
    secrets:
      gh-token: ${{ secrets.PR_TOKEN }}
