name: E2E Tests

on:
  workflow_call:

jobs:
  needs-e2e:
    name: Needs E2E
    runs-on: ubuntu-latest
    outputs:
      needs-e2e: ${{ steps.needs-e2e.outputs.NEEDS_E2E }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # By default, the checkout action checks out the last merge commit for pull requests.
          # Source: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
          # However, we need the head commit (the latest commit pushed to the source branch)
          # because in the workflow, we would like to parse the latest commit tag.
          # Specifying `ref` ensures that the head commit is checked out directly.
          # For a `pull_request` event, the head commit hash is `github.event.pull_request.head.sha`.
          # For a `push` event, the head commit hash is `github.sha`.
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Skip E2E
        id: needs-e2e
        env:
          HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          if git show --format='%B' --no-patch "${HEAD_COMMIT_HASH}" | grep --fixed-strings --quiet '[skip e2e]'; then
              printf '%s\n' "${HEAD_COMMIT_HASH} contains the tag '[skip e2e]' so e2e tests will not run"
              echo "NEEDS_E2E=false" >> "$GITHUB_OUTPUT"
          else
              printf '%s\n' "${HEAD_COMMIT_HASH} does not contain the tag '[skip e2e]' so e2e tests will run"
              echo "NEEDS_E2E=true" >> "$GITHUB_OUTPUT"
          fi

  test-e2e-chrome:
    needs:
      - needs-e2e
    if: ${{ needs.needs-e2e.outputs.needs-e2e == 'true' }}
    uses: ./.github/workflows/e2e-chrome.yml
