name: Get release timelines

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version of the release

jobs:
  get-release-timelines:
    name: Get release timelines
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/github-tools/.github/actions/get-release-timelines@v1
        with:
          version: ${{ inputs.version }}
          runway-app-id: ${{ secrets.RUNWAY_APP_ID }}
          runway-api-key: ${{ secrets.RUNWAY_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
