name: Page load benchmark upload

on:
  workflow_call:
    secrets:
      EXTENSION_BENCHMARK_STATS_TOKEN:
        required: true

jobs:
  page-load-benchmark-upload:
    name: Upload Page Load Benchmarks Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          yarn-custom-url: ${{ vars.YARN_URL }}

      - name: Download page load benchmark results
        uses: actions/download-artifact@v4
        with:
          name: benchmark-results

      - name: Create expected page load benchmark results directory structure
        shell: bash
        run: |
          mkdir -p test-artifacts/benchmarks
          mv benchmark-results.json test-artifacts/benchmarks/benchmark-results.json

      - name: Upload benchmark results (historical data)
        run: .github/scripts/benchmark-stats-commit.sh
        env:
          EXTENSION_BENCHMARK_STATS_TOKEN: ${{ secrets.EXTENSION_BENCHMARK_STATS_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
