name: Page load benchmark

on:
  workflow_call:
    inputs:
      browser-loads:
        description: 'Number of browser loads to perform'
        required: false
        type: string
        default: '10'
      page-loads:
        description: 'Number of page loads per browser'
        required: false
        type: string
        default: '10'

jobs:
  page-load-benchmark-pr:
    name: Run Page Load Benchmarks
    runs-on: ubuntu-latest
    env:
      PR_COMMENT_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.event.repository.name }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          yarn-custom-url: ${{ vars.YARN_URL }}

      - name: Download artifact 'build-dist-browserify'
        uses: actions/download-artifact@v4
        with:
          name: build-dist-browserify

      - name: Install Playwright browsers
        run: yarn playwright install chromium

      - name: Run page load benchmarks
        run: yarn test:e2e:benchmark

      - name: Upload benchmark results (github artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: test-artifacts/benchmarks/benchmark-results.json
