name: Page load benchmark

on:
  workflow_call:
    inputs:
      browser-loads:
        description: 'Number of browser loads to perform'
        required: false
        type: number
        default: 10
      page-loads:
        description: 'Number of page loads per browser'
        required: false
        type: number
        default: 10
      builds-from-run:
        required: true
        type: string
        description: The run ID to get builds from
    secrets:
      EXTENSION_BENCHMARK_STATS_TOKEN:
        required: true

jobs:
  page-load-benchmark-pr:
    name: Run Page Load Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OWNER: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.event.repository.name }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
      BENCHMARK_BROWSER_LOADS: ${{ inputs.browser-loads }}
      BENCHMARK_PAGE_LOADS: ${{ inputs.page-loads }}
      IS_PR_OR_MAIN: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_name == 'main') }}
    steps:
      - name: Checkout and setup environment
        if: ${{ env.IS_PR_OR_MAIN }}
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          use-yarn-hydrate: true

      - name: Download artifact 'build-test-browserify'
        if: ${{ env.IS_PR_OR_MAIN }}
        uses: actions/download-artifact@v4
        with:
          name: build-test-browserify
          github-token: ${{ secrets.GITHUB_TOKEN }} # This is required when downloading artifacts from a different repository or from a different workflow run.
          run-id: ${{ inputs.builds-from-run }} # Download from whatever run the identify-builds job said.

      - name: Install Playwright browsers
        if: ${{ env.IS_PR_OR_MAIN }}
        run: yarn playwright install chromium

      - name: Run page load benchmarks
        if: ${{ env.IS_PR_OR_MAIN }}
        run: yarn test:e2e:benchmark

      - name: Upload benchmark results (github artifacts)
        if: ${{ env.IS_PR_OR_MAIN }}
        uses: actions/upload-artifact@v4
        with:
          name: page-load-benchmark-results
          path: test-artifacts/benchmarks/page-load-benchmark-results.json

      - name: Upload benchmark results (historical data)
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: .github/scripts/benchmark-stats-commit.sh
        env:
          EXTENSION_BENCHMARK_STATS_TOKEN: ${{ secrets.EXTENSION_BENCHMARK_STATS_TOKEN }}
