name: Remove RCA-needed Label

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

permissions:
  issues: write
  contents: read

jobs:
  remove-rca-labels:
    name: Remove RCA-needed Labels
    runs-on: ubuntu-latest
    steps:
      - name: Remove RCA-needed label
        uses: MetaMask/github-tools/.github/actions/remove-rca-needed-label-sheets@v1
        with:
          spreadsheet-id: '1Y16QEnDwZuR3DAQIe3T5LTWy1ye07GNYqxIei_cMg24'
          sheet-name: 'Form Responses 1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          google-application-creds-base64: ${{ secrets.GCP_RLS_SHEET_ACCOUNT_BASE64 }}
