name: Test lint changelog

on:
  workflow_call:

jobs:
  test-lint-changelog:
    name: Test lint changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - name: Validate changelog
        # For a `pull_request` event, the branch is `github.head_ref``.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        run: yarn lint:changelog

      - name: Validate release candidate changelog
        # For a `pull_request` event, the branch is `github.head_ref``.
        # For a `push` event, the branch is `github.ref_name`.
        if: ${{ startsWith(github.head_ref || github.ref_name, 'Version-v') }}
        continue-on-error: true
        run: .circleci/scripts/validate-changelog-in-rc.sh
