name: Validate E2E Page Object usage on modified files

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-e2e-pom-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - name: Run E2E Page Object Usage Validation
        env:
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
          HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          yarn validate-e2e-page-object-usage